project-mos/backend

.github/workflows/cicd.test.yml
=> chore: cicd 테스트 추가

appspec.yml
=> chore: appspec.yml 수정

src/main/java/com/mos/backend/common/infrastructure/EntityFacade.java, src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/presentation/controller/api/StudyController.java, src/main/java/com/mos/backend/studies/presentation/requestdto/StudyCreateRequestDto.java, src/main/java/com/mos/backend/studybenefits/application/StudyBenefitService.java, src/main/java/com/mos/backend/studybenefits/application/responsedto/StudyBenefitResponseDto.java, src/main/java/com/mos/backend/studybenefits/entity/StudyBenefit.java, src/main/java/com/mos/backend/studybenefits/entity/exception/StudyBenefitErrorCode.java, src/main/java/com/mos/backend/studybenefits/infrastructure/StudyBenefitJpaRepository.java, src/main/java/com/mos/backend/studybenefits/infrastructure/StudyBenefitRepository.java, src/main/java/com/mos/backend/studybenefits/infrastructure/StudyBenefitRepositoryImpl.java, src/main/java/com/mos/backend/studybenefits/presentation/controller/api/StudyBenefitController.java, src/main/java/com/mos/backend/studybenefits/presentation/requestdto/StudyBenefitRequestDto.java, src/main/java/com/mos/backend/studyquestions/presentation/requestdto/StudyQuestionCreateRequestDto.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/presentation/controller/api/StudyControllerTest.java, src/test/java/com/mos/backend/studybenefits/application/StudyBenefitServiceTest.java
> close #59 
<br>
1. StudyBenefits 생성|수정|삭제 API
2. StudyBenefits 조회(다 건 조회만) API
3. TC 작성
<br>
이와 동일하게 Question도 개발하려고 합니다.
=> Feat/benefit #59

src/main/java/com/mos/backend/userstudylikes/application/UserStudyLikeService.java, src/main/java/com/mos/backend/userstudylikes/entity/UserStudyLike.java, src/main/java/com/mos/backend/userstudylikes/infrastructure/UserStudyLikeJpaRepository.java, src/main/java/com/mos/backend/userstudylikes/infrastructure/UserStudyLikeRepository.java, src/main/java/com/mos/backend/userstudylikes/infrastructure/UserStudyLikeRepositoryImpl.java, src/main/java/com/mos/backend/userstudylikes/presentation/api/UserStudyLikeRepository.java, src/main/java/com/mos/backend/userstudylikes/presentation/controller/api/UserStudyLikeRepository.java, src/test/java/com/mos/backend/userstudylikes/application/UserStudyLikeServiceTest.java
> close #54
<br>
1. 좋아요 요청
2. 좋아요 취소
3. tc 작성
<br>
=> Feat/likes #54

src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/entity/Study.java, src/main/java/com/mos/backend/studybenefits/entity/exception/StudyBenefitErrorCode.java, src/main/java/com/mos/backend/studyjoins/application/StudyJoinService.java, src/main/java/com/mos/backend/studyjoins/presentation/controller/api/StudyJoinController.java, src/main/java/com/mos/backend/studyquestions/application/StudyQuestionService.java, src/main/java/com/mos/backend/studyquestions/application/responsedto/StudyQuestionResponseDto.java, src/main/java/com/mos/backend/studyquestions/entity/QuestionOption.java, src/main/java/com/mos/backend/studyquestions/entity/StudyQuestion.java, src/main/java/com/mos/backend/studyquestions/entity/StudyQuestionErrorCode.java, src/main/java/com/mos/backend/studyquestions/infrastructure/StudyQuestionJpaRepository.java, src/main/java/com/mos/backend/studyquestions/infrastructure/StudyQuestionRepository.java, src/main/java/com/mos/backend/studyquestions/infrastructure/StudyQuestionRepositoryImpl.java, src/main/java/com/mos/backend/studyquestions/presentation/controller/api/StudyQuestionController.java, src/main/java/com/mos/backend/studyquestions/presentation/requestdto/StudyQuestionCreateRequestDto.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/presentation/controller/api/StudyControllerTest.java, src/test/java/com/mos/backend/studyquestions/application/StudyQuestionServiceTest.java
> close #67
<br>
1. study-join의 @Transactional 수정 (jakarta -> springframework)
2. studyQuestion crud
3. studyQuestion 과 연관된 부분 변경
=> Feat/question #67

src/main/java/com/mos/backend/common/utils/ClientInfoExtractor.java, src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/application/ViewCountService.java, src/main/java/com/mos/backend/studies/presentation/controller/api/StudyController.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/application/ViewCountServiceTest.java
> close #71 
<br>
1. IP 기반 어뷰징 방지 기능 추가
2. 조회수 증가 + 어뷰징 방지를 viewCountService로 클래스 분리
3. tc 작성
<br>
Client에서 IP 추출하는 부분을 Util 클래스로 분리했습니다. 후에 Client에서 다른 정보나, cookie 같은 것을 가져올 때 해당 utill class를 통해 재사용하려고 합니다.
=> Feat/abusing #71

src/main/java/com/mos/backend/common/utils/TimeCalculator.java, src/main/java/com/mos/backend/hotstudies/application/HotStudyEventHandlerDispatcher.java, src/main/java/com/mos/backend/hotstudies/application/HotStudyScoreCalculator.java, src/main/java/com/mos/backend/hotstudies/application/HotStudyScoreUpdater.java, src/main/java/com/mos/backend/hotstudies/application/HotStudyService.java, src/main/java/com/mos/backend/hotstudies/application/hotstudyeventhandler/EventHandler.java, src/main/java/com/mos/backend/hotstudies/application/hotstudyeventhandler/JoinEventHandler.java, src/main/java/com/mos/backend/hotstudies/application/hotstudyeventhandler/LikeEventHandler.java, src/main/java/com/mos/backend/hotstudies/application/hotstudyeventhandler/ViewEventHandler.java, src/main/java/com/mos/backend/hotstudies/entity/HotStudyEventType.java, src/main/java/com/mos/backend/hotstudies/infrastructure/HotStudyJoinRepository.java, src/main/java/com/mos/backend/hotstudies/infrastructure/HotStudyLikeRepository.java, src/main/java/com/mos/backend/hotstudies/infrastructure/HotStudyRepository.java, src/main/java/com/mos/backend/hotstudies/infrastructure/HotStudyViewRepository.java, src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/application/responsedto/StudiesResponseDto.java, src/main/java/com/mos/backend/studies/entity/exception/StudyErrorCode.java, src/main/java/com/mos/backend/studies/presentation/controller/api/StudyController.java, src/main/java/com/mos/backend/userstudylikes/application/UserStudyLikeService.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/hotstudies/application/HotStudyServiceTest.java, src/test/java/com/mos/backend/hotstudies/infrastructure/HotStudyRepositoryTest.java, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/infrastructure/StudyRepositoryTest.java, src/test/java/com/mos/backend/userstudylikes/application/UserStudyLikeServiceTest.java
> close #70
<br>
1. 인기 게시글 handler 개발
2. 게시글 점수 계산 및 업데이트 클래스 개발
3. 인기 게시글 저장 및 조회 로직 개발
4. 시간 계산 유틸 클래스 생성
<br>
우선은 가중치는 다음과 같이 했습니다.
조회수 : 1
좋아요 : 3
지원 : 5
=> Feat/hot #70

src/test/java/com/mos/backend/hotstudies/infrastructure/HotStudyRepositoryTest.java
=> fix(#70): 테스트 깨지는 문제 해결

src/test/java/com/mos/backend/questionanswers/infrastructure/QuestionAnswerRepositoryTest.java, src/test/java/com/mos/backend/studyjoins/infrastructure/StudyJoinRepositoryTest.java, src/test/java/com/mos/backend/studymembers/infrastructure/StudyMemberRepositoryTest.java
> close #48
<br>
- @DirtiesContext 추가
<br>
=> fix: 테스트 환경에서의 db 커넥션 문제 해결

src/main/java/com/mos/backend/studies/application/ViewCountService.java, src/main/java/com/mos/backend/studies/infrastructure/viewcount/ViewCountRedisRepository.java, src/main/java/com/mos/backend/studies/infrastructure/viewcount/ViewCountRepository.java, src/test/java/com/mos/backend/studies/application/ViewCountServiceTest.java, src/test/java/com/mos/backend/studies/infrastructure/viewcount/ViewCountRedisRepositoryTest.java
> close #83
<br>
1. viewCountRepository 생성
2. tc 작성
<br>
=> refactor(#83): viewCountService에서 Redis 분리

src/main/java/com/mos/backend/common/infrastructure/EntityFacade.java, src/main/java/com/mos/backend/users/entity/User.java, src/main/java/com/mos/backend/userschedules/application/UserScheduleService.java, src/main/java/com/mos/backend/userschedules/application/res/UserScheduleRes.java, src/main/java/com/mos/backend/userschedules/entity/UserSchedule.java, src/main/java/com/mos/backend/userschedules/infrastructure/UserScheduleJpaRepository.java, src/main/java/com/mos/backend/userschedules/infrastructure/UserScheduleRepository.java, src/main/java/com/mos/backend/userschedules/infrastructure/UserScheduleRepositoryImpl.java, src/main/java/com/mos/backend/userschedules/presentation/controller/api/UserScheduleController.java, src/main/java/com/mos/backend/userschedules/presentation/req/UserScheduleCreateReq.java, src/main/java/com/mos/backend/userschedules/presentation/req/UserScheduleUpdateReq.java, src/test/java/com/mos/backend/userschedules/application/UserScheduleServiceTest.java, src/test/java/com/mos/backend/userschedules/presentation/controller/api/UserScheduleControllerTest.java
> close #90 
<br>
1. 유저 일정 CRUD api 구현
<br>
=> Feat/user schedule #90

src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studycurriculum/application/StudyCurriculumService.java, src/main/java/com/mos/backend/studycurriculum/application/responsedto/StudyCurriculumResponseDto.java, src/main/java/com/mos/backend/studycurriculum/entity/StudyCurriculum.java, src/main/java/com/mos/backend/studycurriculum/entity/exception/StudyCurriculumErrorCode.java, src/main/java/com/mos/backend/studycurriculum/infrastructure/StudyCurriculumJpaRepository.java, src/main/java/com/mos/backend/studycurriculum/infrastructure/StudyCurriculumRepository.java, src/main/java/com/mos/backend/studycurriculum/infrastructure/StudyCurriculumRepositoryImpl.java, src/main/java/com/mos/backend/studycurriculum/presentation/requestdto/StudyCurriculumCreateRequestDto.java, src/main/java/com/mos/backend/studycurriculum/presentation/requestdto/controller/api/StudyCurriculumController.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/presentation/controller/api/StudyControllerTest.java, src/test/java/com/mos/backend/studycurriculum/application/StudyCurriculumServiceTest.java
> close #84
<br>
1. 스터디 커리큘럼 crud
2. tc 작서
<br>
=> Feat/curriculum #84

src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/presentation/requestdto/StudyCreateRequestDto.java, src/main/java/com/mos/backend/studybenefits/application/StudyBenefitService.java, src/main/java/com/mos/backend/studycurriculum/application/StudyCurriculumService.java, src/main/java/com/mos/backend/studyquestions/application/StudyQuestionService.java, src/main/java/com/mos/backend/studyrules/application/StudyRuleService.java, src/main/java/com/mos/backend/studyrules/application/responsedto/StudyRuleResponseDto.java, src/main/java/com/mos/backend/studyrules/entity/StudyRule.java, src/main/java/com/mos/backend/studyrules/entity/exception/StudyRuleErrorCode.java, src/main/java/com/mos/backend/studyrules/infrastructure/StudyRuleJpaRepository.java, src/main/java/com/mos/backend/studyrules/infrastructure/StudyRuleRepository.java, src/main/java/com/mos/backend/studyrules/infrastructure/StudyRuleRepositoryImpl.java, src/main/java/com/mos/backend/studyrules/presentation/controller/api/StudyRuleController.java, src/main/java/com/mos/backend/studyrules/presentation/requestdto/StudyRuleCreateRequestDto.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/presentation/controller/api/StudyControllerTest.java, src/test/java/com/mos/backend/studybenefits/application/StudyBenefitServiceTest.java, src/test/java/com/mos/backend/studycurriculum/application/StudyCurriculumServiceTest.java, src/test/java/com/mos/backend/studyquestions/application/StudyQuestionServiceTest.java, src/test/java/com/mos/backend/studyrules/application/StudyRuleServiceTest.java
> close #95 
<br>
1. studyRule 도메인 개발(crud)
2.tc 작성
3. 기존 questionNum, sectionId 등 순서에 관련된 검증 로직 수정
<br>
=> Feat/rule #95

src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/application/responsedto/StudyResponseDto.java, src/main/java/com/mos/backend/studies/entity/Study.java, src/main/java/com/mos/backend/studies/presentation/requestdto/StudyCreateRequestDto.java, src/main/java/com/mos/backend/studyrequirements/application/StudyRequirementService.java, src/main/java/com/mos/backend/studyrequirements/application/responsedto/StudyRequirementResponseDto.java, src/main/java/com/mos/backend/studyrequirements/entity/StudyRequirement.java, src/main/java/com/mos/backend/studyrequirements/entity/exception/StudyRequirementErrorCode.java, src/main/java/com/mos/backend/studyrequirements/infrastructure/StudyRequirementJpaRepository.java, src/main/java/com/mos/backend/studyrequirements/infrastructure/StudyRequirementRepository.java, src/main/java/com/mos/backend/studyrequirements/infrastructure/StudyRequirementRepositoryImpl.java, src/main/java/com/mos/backend/studyrequirements/presentation/controller/api/StudyRequirementController.java, src/main/java/com/mos/backend/studyrequirements/presentation/requestdto/StudyRequirementCreateRequestDto.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/studies/StudyFixture.java, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/data/StudyDataInitializer.java, src/test/java/com/mos/backend/studies/infrastructure/StudyRepositoryTest.java, src/test/java/com/mos/backend/studies/presentation/controller/api/StudyControllerTest.java, src/test/java/com/mos/backend/studymembers/infrastructure/StudyMemberRepositoryTest.java, src/test/java/com/mos/backend/studyrequirements/application/StudyRequirementServiceTest.java
> close 97
<br>
1. studyRequirement 도메인 개발 (crud, tc)
2. studyRequirement 도메인 연관 작업(dto, 깨진 테스트 수정)
<br>
=> Feat/requirements #97

.github/workflows/cicd.test.yml, src/main/java/com/mos/backend/studies/application/StudyService.java
1. cicd yml에 bucket, aws credentials 추가
<br>
=> Feat/upload #101

src/main/java/com/mos/backend/common/event/EventType.java, src/main/java/com/mos/backend/hotstudies/infrastructure/event/consumer/HotStudyConsumer.java, src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/application/event/StudyCreatedEventPayload.java, src/main/java/com/mos/backend/studies/application/event/StudyDeletedEventPayload.java, src/main/java/com/mos/backend/studies/application/event/StudyViewedEventPayload.java, src/main/java/com/mos/backend/studies/infrastructure/StudyRepository.java, src/main/java/com/mos/backend/studies/infrastructure/StudyRepositoryImpl.java, src/main/java/com/mos/backend/studies/presentation/controller/api/StudyController.java, src/main/java/com/mos/backend/studybenefits/infrastructure/event/consumer/StudyBenefitConsumer.java, src/main/java/com/mos/backend/studycurriculum/infrastructure/event/consumer/StudyCurriculumConsumer.java, src/main/java/com/mos/backend/studyjoins/application/StudyJoinService.java, src/main/java/com/mos/backend/studyjoins/application/event/StudyJoinEventPayload.java, src/main/java/com/mos/backend/studymembers/infrastructure/event/consumer/StudyMemberConsumer.java, src/main/java/com/mos/backend/studyquestions/infrastructure/event/consumer/StudyQuestionConsumer.java, src/main/java/com/mos/backend/studyrecruitmentimage/infrastructure/event/consumer/StudyRecruitmentImageConsumer.java, src/main/java/com/mos/backend/studyrequirements/infrastructure/event/consumer/StudyRequirementConsumer.java, src/main/java/com/mos/backend/studyrules/infrastructure/event/consumer/StudyRuleConsumer.java, src/main/java/com/mos/backend/userstudylikes/application/UserStudyLikeService.java, src/main/java/com/mos/backend/userstudylikes/application/event/StudyLikeEventPayload.java, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studyjoins/application/StudyJoinServiceTest.java, src/test/java/com/mos/backend/userstudylikes/application/UserStudyLikeServiceTest.java
> close #21
<br>
1. study create 연관 하위 도메인 작업 이벤트 기반으로 수정
2. tc 수정
3. study delete 메서드 개발
<br>
=> Refactor/event #21

.github/workflows/cicd.test.yml
- serviceAccountKey.json 생성 방식 수정
=> chore(#115): git action yml 수정

.github/workflows/cicd.test.yml, docker-compose.yml
> close #129 ]
<br>
- mysql 컨테이너 생성 제거
- driver-class-name 환경 변수로 분리
<br>
=> chore(#129): test cicd 수정

src/main/java/com/mos/backend/common/argumentresolvers/chat/SenderArgumentResolver.java, src/main/java/com/mos/backend/common/jwt/JwtAuthenticationInterceptor.java
main으로 pr 날리고 머지해서 revert 후 재 pr 하겠습니다
=> Revert "refactor: stomp userId 추출 방법 수정"

src/main/java/com/mos/backend/common/argumentresolvers/chat/SenderArgumentResolver.java, src/main/java/com/mos/backend/common/jwt/JwtAuthenticationInterceptor.java
> close #126
<br>
1. stomp 세션을 활용하지 않도록 기존 코드 수정
<br>
저번에 main으로 바로 pr해서 revert 후 release로 재pr 했습니다
=> refactor: stomp userId 추출 방법 수정

src/main/java/com/mos/backend/common/dto/InfinityScrollRes.java, src/main/java/com/mos/backend/common/utils/InfinityScrollUtil.java, src/main/java/com/mos/backend/privatechatmessages/application/PrivateChatMessageService.java, src/main/java/com/mos/backend/privatechatmessages/application/res/PrivateChatMessageRes.java, src/main/java/com/mos/backend/privatechatmessages/infrastructure/PrivateChatMessageQueryDslRepository.java, src/main/java/com/mos/backend/privatechatmessages/infrastructure/PrivateChatMessageRepository.java, src/main/java/com/mos/backend/privatechatmessages/infrastructure/PrivateChatMessageRepositoryImpl.java, src/main/java/com/mos/backend/privatechatmessages/presentation/controller/api/PrivateChatMessageController.java, src/main/java/com/mos/backend/studychatmessages/application/StudyChatMessageService.java, src/main/java/com/mos/backend/studychatmessages/application/res/StudyChatMessageRes.java, src/main/java/com/mos/backend/studychatmessages/infrastructure/StudyChatMessageQueryDslRepository.java, src/main/java/com/mos/backend/studychatmessages/infrastructure/StudyChatMessageRepository.java, src/main/java/com/mos/backend/studychatmessages/infrastructure/StudyChatMessageRepositoryImpl.java, src/main/java/com/mos/backend/studychatmessages/presentation/controller/api/StudyChatMessageController.java, src/test/java/com/mos/backend/common/EntitySaver.java, src/test/java/com/mos/backend/privatechatmessages/application/PrivateChatMessageServiceTest.java, src/test/java/com/mos/backend/studychatmessages/application/StudyChatMessageServiceTest.java
> close #133
<br>
1. 1:1 채팅 메시지 조회
2. 스터디 채팅 메시지 조회
<br>
id 내림차순, no-offset 방식을 적용한 무한스크롤 적용
=> Feat/chat #133

.github/workflows/cicd.test.yml, src/main/java/com/mos/backend/common/jwt/TokenUtil.java, src/main/java/com/mos/backend/users/application/OauthService.java, src/main/resources/application.yml
> close #138
<br>
1. Kakao OAuth의 client-secret 등록
<br>
=> Fix/oauth #138

src/main/resources/application.yml
> close #138
<br>
1. yml에 환경변수 추가
<br>
=> fix: 누락된 yml 환경 변수 추가

src/main/java/com/mos/backend/common/jwt/TokenUtil.java
> close #151
<br>
1. Cookie -> ResponseCookie로 변경 및 samsite 설정
=> refactor: Cookie -> ResponseCookie로 변경

src/main/java/com/mos/backend/common/jwt/JwtAuthenticationFilter.java
> close #154
<br>
- Authentication에 Authority 추가
<br>
=> fix: 인증 성공한 api에 대해 403 에러 발생 문제 해결

src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/application/responsedto/StudyCreateResponseDto.java, src/main/java/com/mos/backend/studies/presentation/controller/api/StudyController.java, src/test/java/com/mos/backend/studies/application/StudyServiceTest.java, src/test/java/com/mos/backend/studies/presentation/controller/api/StudyControllerTest.java
> close #160
<br>
1. 스터디 ID dto로 반환(responseBody)
2. tc 수정
<br>
=> refactor(#160): 스터디 생성 시 ID 반환 방식 수정

src/main/java/com/mos/backend/studyjoins/application/StudyJoinService.java, src/main/java/com/mos/backend/studyjoins/entity/exception/StudyJoinErrorCode.java, src/main/java/com/mos/backend/studyquestions/application/StudyQuestionService.java, src/main/java/com/mos/backend/studyquestions/entity/StudyQuestionErrorCode.java, src/main/resources/messages/messages-error.properties, src/test/java/com/mos/backend/studyjoins/application/StudyJoinServiceTest.java
> close #169
<br>
1. - Notification 이벤트 발생 코드 주석(프론트와 합의 후 다시 사용)
- 질문 답변 검증을 다음과 같이 진행하도록 수정
1. 필수 질문에 답변이 존재하는지 먼저 검증
2. 객관식에 대한 답변일 경우 보기에서 적절하게 골라졌는지 검증
2. StudyQuestionErrorCode에 작성된 StudyJoinErrorCode를 StudyJoinErrorCode로 이동
3. StudyQuestion에 대한 검증을 StudyJoinService에서 하던 것을 StudyQuestionService로 수정. 이후 의존관계 주입 받아 처리
4. 스터디 지원 검증 로직 수정으로 깨진 테스트 수정
<br>
=> Fix/joins #169

src/main/java/com/mos/backend/common/argumentresolvers/chat/SenderArgumentResolver.java, src/main/java/com/mos/backend/common/jwt/JwtAuthenticationFilter.java, src/main/java/com/mos/backend/common/jwt/JwtAuthenticationInterceptor.java, src/main/java/com/mos/backend/common/jwt/TokenUtil.java
> close #181
<br>
1. 토큰 통신 방법 수정
- http -> 쿠키
- stomp -> 헤더
<br>
이번 수정이 마지막이길..
=> refactor: 토큰 통신 방법 수정

src/main/java/com/mos/backend/studyjoins/application/StudyJoinService.java
> close #187
<br>
1. 알림 이벤트 호출 제거
<br>
=> fix: 알림 이벤트 호출 제거

src/main/java/com/mos/backend/studies/application/responsedto/StudiesResponseDto.java, src/main/java/com/mos/backend/studies/infrastructure/StudyQueryDslRepository.java
- startDate, Content 포함해서 반환
> close #190
<br>
1. study 목록 조회 시 responseDto에 startDate, content 추가
2.스터디 조회 쿼리에서 startDate, content도 조회하도록 수정
=> refactor(#190): 스터디 조회 api 수정

src/main/java/com/mos/backend/studymaterials/application/responsedto/ReadStudyMaterialResponseDto.java, src/main/java/com/mos/backend/studymaterials/infrastructure/StudyMaterialJpaRepository.java, src/main/java/com/mos/backend/studynotices/infrastructure/StudyNoticeJpaRepository.java
> close #207 
<br>
1. 스터디 자료 조회 api 수정
- 다 건 조회, 단 건 조회 시 userNickname 포함
- studyMaterial 조회 시 studyMember - User 정보 조회에 발생하는 N + 1 문제 해결 위해 EntityGraph 적용
3. jpa 메서드 오버라이드 시 권고 사항 적용하기 위해 쿼리 메서드와 파라미터에 @NonNull 애노테이션 추가
=> Refactor/materials #207

src/main/java/com/mos/backend/common/event/EventType.java, src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/application/event/StudyUpdatedEventPayload.java, src/main/java/com/mos/backend/studies/entity/Study.java, src/main/java/com/mos/backend/studies/presentation/controller/api/StudyController.java, src/main/java/com/mos/backend/studies/presentation/requestdto/StudyUpdateRequestDto.java, src/main/java/com/mos/backend/studyrecruitmentimage/application/StudyRecruitmentImageService.java, src/main/java/com/mos/backend/studyrecruitmentimage/application/consumer/StudyRecruitmentImageConsumer.java, src/main/java/com/mos/backend/studyrequirements/application/consumer/StudyRequirementConsumer.java, src/test/java/com/mos/backend/studynotices/application/StudyNoticeServiceTest.java, src/test/java/com/mos/backend/studyrecruitmentimage/application/StudyRecruitmentImageServiceTest.java
> close #197 
<br>
1. 스터디 업데이트 api 개발
2. 업데이트 시 발생 이벤트와 관련 consumer 생성
3. consumer를 받아 처리하는 메서드의 파라미터 수정
4. 깨진 테스트 수정
<br>
=> Feat/study update #197

src/main/java/com/mos/backend/attendances/entity/Attendance.java, src/main/java/com/mos/backend/notifications/entity/NotificationLog.java, src/main/java/com/mos/backend/notifications/entity/UserFcmToken.java, src/main/java/com/mos/backend/privatechatmessages/entity/PrivateChatMessage.java, src/main/java/com/mos/backend/questionanswers/entity/QuestionAnswer.java, src/main/java/com/mos/backend/studies/application/StudyService.java, src/main/java/com/mos/backend/studies/infrastructure/StudyJpaRepository.java, src/main/java/com/mos/backend/studies/infrastructure/StudyRepository.java, src/main/java/com/mos/backend/studies/infrastructure/StudyRepositoryImpl.java, src/main/java/com/mos/backend/studybenefits/entity/StudyBenefit.java, src/main/java/com/mos/backend/studychatmessages/entity/StudyChatMessage.java, src/main/java/com/mos/backend/studychatrooms/entity/StudyChatRoom.java, src/main/java/com/mos/backend/studycurriculum/entity/StudyCurriculum.java, src/main/java/com/mos/backend/studyjoins/entity/StudyJoin.java, src/main/java/com/mos/backend/studymaterials/entity/StudyMaterial.java, src/main/java/com/mos/backend/studymemberroles/entity/StudyMemberRole.java, src/main/java/com/mos/backend/studymembers/entity/StudyMember.java, src/main/java/com/mos/backend/studynotices/entity/StudyNotice.java, src/main/java/com/mos/backend/studyquestions/entity/StudyQuestion.java, src/main/java/com/mos/backend/studyrecruitmentimage/entity/StudyRecruitmentImage.java, src/main/java/com/mos/backend/studyrequirements/entity/StudyRequirement.java, src/main/java/com/mos/backend/studyrules/entity/StudyRule.java, src/main/java/com/mos/backend/studyschedulecurriculums/entity/StudyScheduleCurriculum.java, src/main/java/com/mos/backend/studyschedules/entity/StudySchedule.java, src/main/java/com/mos/backend/userstudylikes/entity/UserStudyLike.java
> close #108
<br>
1. hibernate @OnDelete 옵션 사용해서 부모 엔티티 삭제 시 자식 엔티티 삭제 처리
<br>
=> feat(#108): 스터디 삭제 시 하위 연관 엔티티 삭제

src/main/java/com/mos/backend/common/config/SecurityConfig.java, src/main/java/com/mos/backend/userstudylikes/application/UserStudyLikeService.java, src/main/java/com/mos/backend/userstudylikes/application/response/LikesResponseDto.java, src/main/java/com/mos/backend/userstudylikes/infrastructure/UserStudyLikeQueryDslRepository.java, src/main/java/com/mos/backend/userstudylikes/infrastructure/UserStudyLikeRepository.java, src/main/java/com/mos/backend/userstudylikes/infrastructure/UserStudyLikeRepositoryImpl.java, src/main/java/com/mos/backend/userstudylikes/presentation/controller/api/UserStudyLikeController.java
> close #235
<br>
1. 잘못된 클래스명 수정 : UserStudyLikeRepository -> UserStudyLikeController
2. studyId 목록을 받아서 [studyId, likedCount, isLiked ] 반환하는 api 개발
=> Refactor/likes #235

src/main/java/com/mos/backend/privatechatrooms/application/PrivateChatRoomService.java, src/main/java/com/mos/backend/privatechatrooms/infrastructure/PrivateChatRoomJpaRepository.java, src/main/java/com/mos/backend/privatechatrooms/infrastructure/PrivateChatRoomRepository.java, src/main/java/com/mos/backend/privatechatrooms/infrastructure/PrivateChatRoomRepositoryImpl.java, src/test/java/com/mos/backend/privatechatrooms/application/PrivateChatRoomServiceTest.java
> close #243
<br>
1. 채팅방 조회 시 status=VISIBLE인 데이터만 조회하여 해결
<br>
=> fix: 나의 채팅방 조회 시 PrivateChatMessageErrorCode.NOT_FOUND 에러 발생 해결

src/main/java/com/mos/backend/common/event/EventType.java, src/main/java/com/mos/backend/studynotices/application/StudyNoticeService.java, src/main/java/com/mos/backend/studynotices/application/event/ImportantNoticeChangedEventPayload.java, src/main/java/com/mos/backend/userstudysettings/application/UserStudySettingService.java, src/main/java/com/mos/backend/userstudysettings/application/consumer/UserStudySettingConsumer.java, src/main/java/com/mos/backend/userstudysettings/infrastructure/UserStudySettingQueryDslRepository.java, src/main/java/com/mos/backend/userstudysettings/infrastructure/UserStudySettingRepository.java, src/main/java/com/mos/backend/userstudysettings/infrastructure/UserStudySettingRepositoryImpl.java, src/test/java/com/mos/backend/studynotices/application/StudyNoticeServiceTest.java
> close #254
<br>
1. 중요 공지(상단 고정 공지) 생성 및 변경 시 event 발행
2. 중요 공지 생섳 및 변경 event 발행 시  useStudySettings 에서 해당 스터디 멤버의 모든 상단 고정 공지 노출 여부를 true로 변경
3. tc 작성
=> Feat/notice #254

src/main/java/com/mos/backend/studychatrooms/entity/StudyChatRoom.java, src/main/java/com/mos/backend/studychatrooms/infrastructure/StudyChatRoomJpaRepository.java
> close #260
<br>
1. StudyChatRoom Status 제거
<br>
=> Refactor: StudyChatRoom Status 제거

src/main/java/com/mos/backend/privatechatmessages/presentation/controller/api/PrivateChatMessageController.java, src/main/java/com/mos/backend/studychatmessages/presentation/controller/api/StudyChatMessageController.java
> close #278
<br>
1. 무한 스크롤이 적용된 API의 파라미터명 lastElementId로 통일
=> refactor: lastElementId로 파라미터명 및 서비스 호출 통일

src/main/java/com/mos/backend/banners/application/BannerService.java, src/main/java/com/mos/backend/banners/application/responsedto/BannerResponseDto.java, src/main/java/com/mos/backend/banners/entity/Banner.java, src/main/java/com/mos/backend/banners/entity/exception/BannerErrorCode.java, src/main/java/com/mos/backend/banners/infrastructure/BannerJpaRepository.java, src/main/java/com/mos/backend/banners/infrastructure/BannerRepository.java, src/main/java/com/mos/backend/banners/infrastructure/BannerRepositoryImpl.java, src/main/java/com/mos/backend/banners/presentation/BannerController.java, src/main/java/com/mos/backend/banners/presentation/requestdto/BannerCreateRequestDto.java, src/main/java/com/mos/backend/banners/presentation/requestdto/BannerUpdateRequestDto.java, src/main/java/com/mos/backend/common/config/SecurityConfig.java, src/main/java/com/mos/backend/studymaterials/application/UploadType.java, src/main/resources/messages/messages-error.properties
> close #281
<br>
1. 배너 crud 작업
2. 배너에 순서를 넣고, 생성-수정-삭제 시 배너의 순서들이 조정될 수 있도록 함.
<br>
tc 작성을 못했는데, postman으로 정상 작동은 확인했습니다. 일단 먼저 올려서 프론트에서 작업할 수 있도록 하고 후에 보충하겠습니다.
=> Feat/banner #281

src/main/java/com/mos/backend/notifications/application/NotificationLogService.java, src/main/java/com/mos/backend/notifications/application/dto/NotificationResponseDto.java, src/main/java/com/mos/backend/notifications/application/dto/NotificationUnreadCountDto.java, src/main/java/com/mos/backend/notifications/entity/NotificationLog.java, src/main/java/com/mos/backend/notifications/entity/NotificationReadStatus.java, src/main/java/com/mos/backend/notifications/infrastructure/notificationlog/NotificationLogJpaRepository.java, src/main/java/com/mos/backend/notifications/infrastructure/notificationlog/NotificationLogQueryDslRepository.java, src/main/java/com/mos/backend/notifications/infrastructure/notificationlog/NotificationLogRepository.java, src/main/java/com/mos/backend/notifications/infrastructure/notificationlog/NotificationLogRepositoryImpl.java, src/main/java/com/mos/backend/notifications/presentation/controller/api/NotificationLogController.java
> close #286
<br>
1. 알림 단 건 조회(읽음 처리)
2. 목록 조회(페이징, 읽음 상태 필터링)
3. 안읽은 수 조회
=> Feat/mailbox #286
